services:
  saas-backend:
    env_file: .env
    volumes:
      - ./src:/app/src

  saas-frontend:
    env_file: ./frontend/.env
    command: ["pnpm", "run", "dev"]
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/eslint.config.mjs:/app/eslint.config.mjs
      - ./frontend/components.json:/app/components.json
