"""initial migration

Revision ID: 98ffd4d3b7ec
Revises: 
Create Date: 2025-07-03 19:06:34.919572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ffd4d3b7ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_expires_at'), 'blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_blacklist_jti'), 'blacklist', ['jti'], unique=True)
    op.create_table('price_id',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_id_id'), 'price_id', ['id'], unique=True)
    op.create_index(op.f('ix_price_id_name'), 'price_id', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=False)
    op.create_table('stripe_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subcription_plan', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_metadata_expires_at'), 'stripe_metadata', ['expires_at'], unique=False)
    op.create_index(op.f('ix_stripe_metadata_id'), 'stripe_metadata', ['id'], unique=True)
    op.create_index(op.f('ix_stripe_metadata_subcription_plan'), 'stripe_metadata', ['subcription_plan'], unique=False)
    op.create_index(op.f('ix_stripe_metadata_user_id'), 'stripe_metadata', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_metadata_user_id'), table_name='stripe_metadata')
    op.drop_index(op.f('ix_stripe_metadata_subcription_plan'), table_name='stripe_metadata')
    op.drop_index(op.f('ix_stripe_metadata_id'), table_name='stripe_metadata')
    op.drop_index(op.f('ix_stripe_metadata_expires_at'), table_name='stripe_metadata')
    op.drop_table('stripe_metadata')
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_id_name'), table_name='price_id')
    op.drop_index(op.f('ix_price_id_id'), table_name='price_id')
    op.drop_table('price_id')
    op.drop_index(op.f('ix_blacklist_jti'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_expires_at'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
