on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-test-workflow.yml
  
  version:
    uses: ./.github/workflows/version.yml
    needs: [test]
    secrets:
      git_token: ${{ secrets.GPAT_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [test, version]

    strategy:
      matrix:
        include:
          - dockerfile: ./.deploy/docker-images/Dockerfile.frontend
            dockerhub_repo: saas-template-frontend
          - dockerfile: ./.deploy/docker-images/Dockerfile.backend
            dockerhub_repo: saas-template-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: ./.github/actions/docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_repo: ${{ matrix.dockerhub_repo }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ${{ matrix.dockerfile }}
          version: ${{ steps.version.outputs.version }}

