name: Push to Helm

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
        repo_token:
            required: true

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push Helm Chart
        uses: ./.github/actions/push-to-helm
        with:
          app-repo-token: ${{ secrets.repo_token }}
          version: ${{ inputs.version }}
