name: Pytest

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set env
        run: echo "ENV=test" >> $GITHUB_ENV

      - name: Set UV Config
        run: pdm config use_uv true 

      - name: Install pdm
        run: pip install pdm

      - name: Install project dependencies
        run: pdm install

      - name: Run tests
        run: PYTHONPATH=. pdm run pytest -v -ra src/saas_backend/tests